### ISSUE TITLE
Installation via brew failed: Operation not permitted

### ISSUE THREAD

**Issue by AwlsomeAlex** [Free-GPGMail/Free-GPGMail#53]
Tried to install Free-GPGMail using the Homebrew Cask but got the following output:

```==> Moving Generic Artifact 'Free-GPGMail_6.mailbundle' to '/Users/awlsomealex/L
mkdir: /Users/awlsomealex/Library/Mail/Bundles: Operation not permitted
==> Purging files for version 6,2022.1.1, of Cask free-gpgmail
Error: Failure while executing; '/usr/bin/sudo -E -- /bin/mkdir -p /Users/awlsomealex/Library/Mail/Bundles' exited with 1. Here's the output:
mkdir: /Users/awlsomealex/Library/Mail/Bundles: Operation not permitted
```
Using the default Terminal.app and the latest Homebrew under macOS Monterey 12.4 (Apple Silicon)

This was fixed by granting Terminal.app 'Full Disk Access'. You should probably add a comment in the installation part about that being a requirement.

**Comment by bnavigator** [comment]
I am not sure if this is within the scope of Free-GPGMail or even of homebrew. Not giving your shell filesystem access seems dumb to me. But I am a Linux user, not a Mac user.

**Comment by msimkins** [comment]
This is a MacOS protection feature - you have to user Finder to install the bundle

**Comment by bnavigator** [comment]
1. What do you expect when you execute a command in your own terminal to install stuff? Surely you must do such things where you have filesystem access.
2. Should be fixed on homebrew's side (they did so with the zap command: https://github.com/Homebrew/brew/pull/7587)
3. maybe the cask should not install into `#{ENV["HOME"]}/Library/Mail/` but into homebrew's usual prefix /usr/local/Library/Mail. Somebody able to check that? @jpbernius, @EivindArvesen, @samford, @ChristianKraemer

**Comment by jpbernius** [comment]
So at least for me, it installs the bundle as `~/Library/Mail/Bundles/Free-GPGMail_6.mailbundle` and this works just fine.
However, when upgrading to the latest version I encountered an interesting error:
```
Error: free-gpgmail: It seems the Generic Artifact source '/Users/***/Library/Mail/Bundles/Free-GPGMail_6.mailbundle' is not there.
```

which I could resolve by uninstalling and reinstalling the `free-gpgmail` cask.

**Comment by lotyp** [comment]
Sorry, read again, and understood to enable full disk access

**Comment by albe-rosado** [comment]
Enabling filesystem access to iTerm worked for me. MacOS Monterrey 12.4 (Intel).

**Comment by asperling** [comment]
See https://gitlab.com/gnachman/iterm2/-/wikis/fulldiskaccess for how to enable fill disk access.

This issue should be closed.

**Comment by lotyp** [comment]
> See [gitlab.com/gnachman/iterm2/-/wikis/fulldiskaccess](https://gitlab.com/gnachman/iterm2/-/wikis/fulldiskaccess) for how to enable fill disk access.
> 
> This issue should be closed.

if you are fourth, who found this issue... then probably this should be mentioned in GPGMAil's FAQ ? 😀

**Comment by bnavigator** [comment]
The full disk access is only a work around. This should be resolved on the homebrew side (homebrew itself or in the brew formula) (https://github.com/Free-GPGMail/Free-GPGMail/issues/53#issuecomment-1140487113)

**Comment by jl-stellar** [comment]
FWIW: The issue when upgrading still exists and is not caused by the disk access permission for the terminal app (I have full disk access enabled for the terminal).
When I tried to upgrade today, I got the same error:
```
Error: free-gpgmail: It seems the Generic Artifact source '/Users/jl-stellar/Library/Mail/Bundles/Free-GPGMail_7.mailbundle' is not there.
```
The plugin was still accessible in Apple Mail, but showed the old version 7.0.
After a restart of the app, the plugin was gone from Apple Mail (Tab in settings gone, and plugn no longer listed under "Manage Plugins").
Running `brew upgrade` again resulted in the same error. However, running `brew install --cask free-gpgmail' resulted in the error "is already installed".
What worked in the end was `brew reinstall --cask free-gpgmail`. The command was executed successfully and after a restart of Apple Mail, the plugin could again be activated under "Manage Plugins" and then was back and working.

**Comment by bnavigator** [comment]
> FWIW: The issue when upgrading still exists and is not caused by the disk access permission for the terminal app

Which means that you encounter a completely different bug. Continue discussion in #81

**Comment by IndySweeney** [comment]
Easy fix.

In System Settings -> Privacy & Security -> (right side) Full-Disk Access -> Terminal  --- Slder to the right.

This will allow terminal to modify the filesystem and install the plugin.   Once you do this, in Mail you need to go to settings -> General ->  Manage Plug-In button (bottom of screen)  and enable the plugin.   By default in my case it was disabled.
